=== tripluo/jrouter/src/main/resources/jrouter-1.6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.6">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>
    <xsd:annotation>
        <xsd:documentation>
            <![CDATA[
            JRouter Schema, version 1.6 Authors: sunjumper@163.com.
            This defines a simple and consistent way of creating components, managed by a JRouter ActionFactory,
            read by net.jrouter.config.Configuration.
            ]]>
        </xsd:documentation>
    </xsd:annotation>
    <!-- main -->
    <xsd:element name="jrouter">
        <xsd:annotation>
            <xsd:documentation>
                <![CDATA[
                The top level (typically root) element.
                ]]>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="1" ref="action-factory"/>
                <xsd:choice minOccurs="0" maxOccurs="unbounded">
                    <xsd:element ref="action"/>
                    <xsd:element ref="interceptor"/>
                    <xsd:element ref="interceptor-stack"/>
                    <xsd:element ref="result-type"/>
                    <xsd:element ref="result"/>
                    <xsd:element ref="component-scan"/>
                    <xsd:element ref="include"/>
                    <xsd:element ref="aop-config"/>
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="action-factory">
        <xsd:annotation>
            <xsd:documentation source="java:net.jrouter.ActionFactory">
                <![CDATA[
                The JRouter ActionFactory configuration.
                ]]>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
            </xsd:sequence>
            <xsd:attribute name="class" use="optional">
                <xsd:annotation>
                    <xsd:documentation source="java:java.lang.Class">
                        <![CDATA[
                        The class of ActionFactory.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="action">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="path"/>
            </xsd:sequence>
            <xsd:attribute name="class" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="path">
        <xsd:annotation>
            <xsd:documentation>
                <![CDATA[
                The specified path in an Action; see the '<action>' element.
                ]]>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
            </xsd:sequence>
            <xsd:attribute name="name" use="required">
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[
                        The specified name of a action path, without suffix.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="interceptor">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
            </xsd:sequence>
            <xsd:attribute name="class" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="interceptor-stack">
        <xsd:complexType>
            <xsd:attribute name="class" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="result-type">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
            </xsd:sequence>
            <xsd:attribute name="class" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="result">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
            </xsd:sequence>
            <xsd:attribute name="class" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="component-scan">
        <xsd:annotation>
            <xsd:documentation>
                <![CDATA[
                Scans the classpath for annotated components of action, interceptorStack, interceptor, resultType, result.
                By default, the JRouter-provided @Action, @Interceptor, @InterceptorStack, @Result and @ResultType stereotypes will be detected.
                ]]>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="package" use="required">
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[
                        The comma-separated list of included packages to scan for annotated components.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="includeExpression">
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[
                        The comma-separated list of expression classes from the included package. The default value is ".**".
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="excludeExpression">
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[
                        The comma-separated list of excluded expression classes.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="include">
        <xsd:annotation>
            <xsd:documentation source="java:org.springframework.core.io.Resource">
                <![CDATA[
                Specifies an XML bean definition resource to import.
                ]]>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="file" use="required">
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[
                    The absolute resource location of the XML (bean definition) file to import, for example "/myImport.xml" or "/includes/myImport.xml".
                    ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="property">
        <xsd:complexType>
            <xsd:attribute name="name" use="required"/>
            <xsd:attribute name="value" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <!-- aop -->
    <xsd:element name="aop-config">
        <xsd:annotation>
            <xsd:documentation>
                <![CDATA[
                The aop configuration element.
                ]]>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <!--<xsd:element minOccurs="0" maxOccurs="unbounded" ref="aop-interceptor-stack"/>-->
                <xsd:element minOccurs="0" maxOccurs="unbounded" ref="aop-action"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="aop-action">
        <xsd:annotation>
            <xsd:documentation>
                <![CDATA[
                Modify the existed matching actions' interceptors with specified interceptors and interceptor-stacks.
                ]]>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="matches" use="required">
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[
                    The matching path of actions'.
                    ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="interceptors">
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[
                    The comma-separated list of existed interceptors' names.
                    ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="interceptor-stacks">
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[
                    The comma-separated list of existed interceptor-stacks' names.
                    ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="type" use="required" type="aop-type">
                <xsd:annotation>
                    <xsd:documentation>
                        <![CDATA[
                    Type of aop operation.
                    ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <!-- aop types -->
    <xsd:simpleType name="aop-type">
        <xsd:restriction base="xsd:NMTOKEN">
            <xsd:enumeration value="add-before"/>
            <xsd:enumeration value="add-after"/>
            <xsd:enumeration value="override"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== tripluo/jrouter/src/test/resources/jrouter_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<jrouter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../main/resources/jrouter-1.6.xsd">

    <action-factory class="jrouter.impl.PathActionFactory">
        <property name="defaultInterceptorStack" value="empty"/>
        <property name="defaultResultType" value="empty"/>
        <property name="pathSeparator" value="/"/>
        <property name="extension" value="."/>
        <property name="actionCacheNumber" value="100000"/>
        <property name="converterFactory" value="jrouter.impl.MultiParameterConverterFactory"/>
        <property name="notExist" value="-1-1-1"/>
    </action-factory>

    <!-- interceptor -->
    <interceptor class="jrouter.interceptor.SampleInterceptor"/>

    <!-- interceptor-stack -->
    <interceptor-stack class="jrouter.interceptor.DefaultInterceptorStack"/>

    <!-- result-type -->
    <result-type class="jrouter.result.DefaultResult"/>

    <!-- result -->
    <result class="jrouter.result.DefaultResult"/>

    <!-- demo interceptor-stack -->
    <interceptor-stack class="jrouter.interceptor.DemoInterceptor"/>

    <!-- demo intercepror -->
    <interceptor class="jrouter.interceptor.DemoInterceptor">
        <property name="value" value="demo interceptor"/>
        <property name="number" value="10000"/>
        <property name="null" value="not supported"/>
    </interceptor>

    <!-- demo result-type -->
    <result-type class="jrouter.result.DemoResult">
        <property name="value" value="demo result"/>
        <property name="null" value="not supported"/>
    </result-type>

    <!-- demo result -->
    <result class="jrouter.result.DemoResult"/>

    <!-- demo action -->
    <action class="jrouter.SimpleAction">
        <property name="string" value="admin"/>
        <property name="number" value="300"/>
        <property name="number" value="200"/>
        <property name="number" value="100"/>
        <property name="null" value="not supported"/>

        <path name="/test/inject2">
            <property name="number" value="200"/>
            <property name="null_path_value" value="-1-1-1"/>
        </path>
    </action>
</jrouter>

=== tripluo/jrouter/src/test/resources/jrouter_autoscan.xml
<?xml version="1.0" encoding="UTF-8"?>
<jrouter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../main/resources/jrouter-1.6.xsd">

    <action-factory class="jrouter.impl.PathActionFactory">
        <property name="defaultInterceptorStack" value="empty"/>
        <property name="defaultResultType" value="empty"/>
        <property name="extension" value="."/>
        <property name="actionCacheNumber" value="100000"/>
    </action-factory>

    <!-- result -->
    <result-type class="jrouter.result.DefaultResult"/>

    <!-- demo intercepror -->
    <interceptor class="jrouter.interceptor.DemoInterceptor">
        <property name="value" value="demo interceptor"/>
        <property name="number" value="10000"/>
        <property name="null" value="not supported"/>
    </interceptor>

    <!-- demo result-type -->
    <result-type class="jrouter.result.DemoResult">
        <property name="value" value="demo result"/>
        <property name="null" value="not supported"/>
    </result-type>

    <!-- demo result -->
    <result class="jrouter.result.DemoResult"/>

    <!-- demo action -->
    <action class="jrouter.SimpleAction">
        <property name="string" value="admin"/>
        <property name="number" value="300"/>
        <property name="number" value="200"/>
        <property name="number" value="100"/>
        <property name="null" value="not supported"/>

        <path name="/test/inject2">
            <property name="number" value="200"/>
        </path>
    </action>

    <!-- scan classes, use ',' as separate -->
    <component-scan package="jrouter"
                    excludeExpression="jrouter.result.*, jrouter.TestDuplicate*.**"/>
</jrouter>
